import * as React from "react";
import { useState, useContext } from 'react';
import { MyContext } from '../components/MyProvider';
import { Image } from "expo-image";
import { Button } from "react-native-paper";
import { TouchableOpacity } from 'react-native';
import { StyleSheet, Text, View, TextInput } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { useNavigation } from '@react-navigation/native';  


const IPhone144 = () => {

  const [ gifterEmail, setGifterEmail ] = useState('');
  const navigation = useNavigation();  
  const { sharedGifterEmail, setSharedGifterEmail } = useContext(MyContext);




  const handleSubmit = () => {
    setSharedGifterEmail(gifterEmail);
  };

  return (
    <View style={styles.iphone143}>
      <View style={styles.frame}>
    
  
        <View style={styles.frame1}>
        <TouchableOpacity 
          onPress={() => navigation.navigate('IPhone143')}   
          style={{marginTop: 40}}      
          >
          <Image
            style={styles.icon}
            contentFit="cover"
            source={require("../assets/icon.png")}
          />
        </TouchableOpacity>
          <Text style={styles.newBundle}>New Bundl</Text>
        </View>
      </View>
      <View style={styles.frame2}>
        <View style={styles.frame3}>
            <View style={styles.frame4}>
                <View style={styles.textFields}>
                  <Text style={styles.whoIsThis}>What is your email?</Text>
                </View>
                <TextInput
                style={[styles.egWhatDo, styles.of3Typo]}
                placeholder="Your email address"
                placeholderTextColor="#cdcdcd"
                value={gifterEmail}
                onChangeText={text => setGifterEmail(text)}
                />
              </View>
        </View>
        <View style={styles.progressIndicatorContainer}>
                  <Text style={styles.of3}>2 of 8</Text>


                  <View style={styles.frame5}>
                    <View style={styles.progressIndicator}>
                      <View style={styles.progressIndicator1} />
                      <LinearGradient
                        style={styles.progressIndicator11}
                        locations={[0]}
                        colors={["#d49797"]}
                      />
                      <View style={styles.progressIndicator2} />
                      <View style={styles.progressIndicator3} />
                    </View>
                    <View style={styles.next}>
                        <View style={styles.primaryDefault}>
                        <Button
                            style={[styles.frame1, styles.frameFlexBox]}
                            mode="contained"
                            labelStyle={styles.frameBtn}
                            onPress={() => {
                              handleSubmit();
                              navigation.navigate("IPhone145");
                            }}
                            contentStyle={styles.frameBtn1}
                          >
                            Next
                          </Button>
              </View>
              </View>
              </View>
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  frameIcon: {
    position: "relative",
    width: 380,
    height: 44,
    overflow: "hidden",
  },
  of3Typo: {
    fontFamily: "Inter-SemiBold",
    fontWeight: "600",
    position: "absolute",
    marginLeft: -20,
    marginTop: 20
  },
  egWhatDo: {
    width: "82.05%",
    top: "32.94%",
    fontSize: 22,
    left: "8.72%",
  },
  icon: {
    position: "relative",
    width: 13,
    height: 18,
  },
  newBundle: {
    position: "relative",
    fontSize: 15,
    letterSpacing: 0.1,
    fontWeight: "600",
    fontFamily: "Inter-SemiBold",
    color: "#14304a",
    textAlign: "center",
    marginLeft: 105,
    marginTop: 30
  },
  frame1: {
    width: 206,
    height: 58,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    marginRight: 116,
    },
  frame: {
    width: 420,
    height: 129,
    overflow: "hidden",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  whoIsThis: {
    position: "relative",
    fontSize: 25,
    letterSpacing: 0.1,
    fontWeight: "600",
    fontFamily: "Inter-SemiBold",
    color: "#14304a",
    textAlign: "left",
  },
  textFields: {
    width: 257,
    height: 34,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    marginRight: 69,
    },
  fullName: {
    fontSize: 22,
    letterSpacing: 0.1,
    fontWeight: "600",
    fontFamily: "Inter-SemiBold",
    color: "#838383",
    textAlign: "left",
    height: 27,
    marginRight: 216,
    marginTop: 16,
  },
  frame4: {
    width: 326,
    height: 160,
    overflow: "hidden",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
  },

  frame3: {
    width: 328,
    height: 180,
    overflow: "hidden",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-end",
  },
  progressIndicatorContainer: {
    flex: 1,
    paddingRight: 20,  // Adjusted padding
    paddingLeft: 20,   // Added padding
    justifyContent: 'flex-end',
    marginBottom: 20,
  },
  of3: {
    fontSize: 13,
    letterSpacing: 0.1,
    fontWeight: "600",
    fontFamily: "Inter-SemiBold",
    color: "#14304a",
    textAlign: "right",
    height: 16,
    marginLeft: 20,  // Adjusted margin
    marginBottom: 5,
  },
  progressIndicator1: {
    position: "absolute",
    height: "100%",
    width: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    borderRadius: 50,
    backgroundColor: "#f0f0f0",
  },
  input: {
    height: 60,
    paddingLeft: 2,
  }, 
  progressIndicator11: {
    position: "absolute",
    height: "100%",
    width: "25.00%",
    top: "0%",
    right: "68.5%",
    bottom: "0%",
    left: "0%",
    borderRadius: 50,
    backgroundColor: "transparent",
  },
  progressIndicator2: {
    position: "absolute",
    height: "100%",
    width: "66.67%",
    top: "0%",
    right: "33.33%",
    bottom: "0%",
    left: "0%",
    borderRadius: 50,
    backgroundColor: "#1a28a9",
    display: "none",
  },
  progressIndicator3: {
    position: "absolute",
    height: "100%",
    width: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
    borderRadius: 50,
    backgroundColor: "#1a28a9",
    display: "none",
  },
  progressIndicator: {
    width: 327,
    height: 8,
    marginLeft: 1,
  },
  signUp: {
    fontSize: 15,
    letterSpacing: 0.1,
    fontWeight: "700",
    fontFamily: "Inter-Bold",
    color: "#fff",
    textAlign: "center",
  },
  // primaryDefault: {
  //   alignSelf: "stretch",
  //   borderRadius: 32,
  //   backgroundColor: "#d49797",
  //   flexDirection: "column",
  //   paddingHorizontal: 32,
  //   paddingVertical: 19,
  //   alignItems: "center",
  //   justifyContent: "center",  // Change to 'center'
  // },
  frameBtn: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    fontFamily: "Inter-Bold",
  },
  frameFlexBox: {
    alignItems: "center",
    overflow: "hidden",
    marginLeft: 100
  },
  frameBtn1: {
    height: 60,
    width: 206,
    backgroundColor: '#d49797', 
  },
  next: {
    width: 327,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: 56,
    marginLeft: 1,
    marginTop: 24,
  },
  frame5: {
    width: 328,
    height: 88,
    overflow: "hidden",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 4,
  },
  frame2: {
    width: 328,
    height: 700,
    overflow: "hidden",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 0,
  },
  bg: {
    position: "relative",
    backgroundColor: "#d1d5db",
    width: 390,
    height: 54,
  },
  dictationIcon: {
    position: "relative",
    width: 16,
    height: 26,
  },
  emojiIcon: {
    position: "relative",
    width: 28,
    height: 28,
  },
  rectangleIcon: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: -1,
    left: 0,
    borderRadius: 6,
    maxWidth: "100%",
    overflow: "hidden",
    maxHeight: "100%",
  },
  label: {
    position: "absolute",
    top: "26.19%",
    left: 0,
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
    width: 92,
  },
  return: {
    position: "absolute",
    height: "16.22%",
    width: "23.85%",
    top: "62.55%",
    right: "0%",
    bottom: "21.24%",
    left: "76.15%",
  },
  label1: {
    position: "absolute",
    top: "26.19%",
    left: 0,
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
    width: 189,
  },
  space: {
    position: "absolute",
    height: "16.22%",
    width: "49.32%",
    top: "62.55%",
    right: "25.47%",
    bottom: "21.24%",
    left: "25.2%",
  },
  label2: {
    position: "absolute",
    top: "26.19%",
    left: 0,
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
    width: 90,
  },
  view: {
    position: "absolute",
    height: "16.22%",
    width: "23.58%",
    top: "62.55%",
    right: "76.42%",
    bottom: "21.24%",
    left: "0%",
  },
  label3: {
    position: "absolute",
    top: "26.19%",
    left: 0,
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 21,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
    width: 44,
  },
  keyLight: {
    position: "absolute",
    height: "100%",
    width: "100%",
    top: "0%",
    right: "0%",
    bottom: "0%",
    left: "0%",
  },
  deleteButtonIcon: {
    position: "relative",
    width: 24,
    height: 17,
  },
  delete: {
    position: "absolute",
    height: "16.22%",
    width: "11.38%",
    top: "41.7%",
    right: "0%",
    bottom: "42.08%",
    left: "88.62%",
  },
  rectangle: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  symbol: {
    position: "absolute",
    marginTop: -12.58,
    top: "50%",
    left: "48.07%",
    fontSize: 23,
    letterSpacing: -1,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
  },
  shiftIcon: {
    position: "absolute",
    height: "39.18%",
    width: "44.95%",
    top: "29.05%",
    right: "27.29%",
    bottom: "31.77%",
    left: "27.76%",
    maxWidth: "100%",
    overflow: "hidden",
    maxHeight: "100%",
  },
  shift: {
    position: "absolute",
    height: "16.22%",
    width: "11.38%",
    top: "41.7%",
    right: "88.62%",
    bottom: "42.08%",
    left: "0%",
  },
  rectangle1: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  symbol1: {
    position: "absolute",
    marginTop: -13.58,
    top: "50%",
    left: "15.63%",
    fontSize: 23,
    letterSpacing: -1,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
  },
  m: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "41.7%",
    right: "14.91%",
    bottom: "42.08%",
    left: "76.42%",
  },
  rectangle2: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  symbol2: {
    position: "absolute",
    marginTop: -13.58,
    top: "50%",
    left: "21.88%",
    fontSize: 23,
    letterSpacing: -1,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
  },
  n: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "41.7%",
    right: "25.2%",
    bottom: "42.08%",
    left: "66.12%",
  },
  rectangle3: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  symbol3: {
    position: "absolute",
    marginTop: -13.58,
    top: "50%",
    left: "25%",
    fontSize: 23,
    letterSpacing: -1,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
  },
  b: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "41.7%",
    right: "35.5%",
    bottom: "42.08%",
    left: "55.83%",
  },
  rectangle4: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  v: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "41.7%",
    right: "45.53%",
    bottom: "42.08%",
    left: "45.8%",
  },
  rectangle5: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  c: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "41.7%",
    right: "55.83%",
    bottom: "42.08%",
    left: "35.5%",
  },
  rectangle6: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  x: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "41.7%",
    right: "65.85%",
    bottom: "42.08%",
    left: "25.47%",
  },
  rectangle7: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  z: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "41.7%",
    right: "76.15%",
    bottom: "42.08%",
    left: "15.18%",
  },
  rectangle8: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  symbol8: {
    position: "absolute",
    marginTop: -13.58,
    top: "50%",
    left: "28.13%",
    fontSize: 23,
    letterSpacing: -1,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
  },
  l: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "4.88%",
    bottom: "62.93%",
    left: "86.45%",
  },
  rectangle9: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  k: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "15.18%",
    bottom: "62.93%",
    left: "76.15%",
  },
  rectangle10: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  j: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "25.2%",
    bottom: "62.93%",
    left: "66.12%",
  },
  rectangle11: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  h: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "35.5%",
    bottom: "62.93%",
    left: "55.83%",
  },
  rectangle12: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  g: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "45.53%",
    bottom: "62.93%",
    left: "45.8%",
  },
  rectangle13: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  f: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "55.83%",
    bottom: "62.93%",
    left: "35.5%",
  },
  rectangle14: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  d: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "65.85%",
    bottom: "62.93%",
    left: "25.47%",
  },
  rectangle15: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  s: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "76.15%",
    bottom: "62.93%",
    left: "15.18%",
  },
  rectangle16: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  a: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "20.85%",
    right: "86.18%",
    bottom: "62.93%",
    left: "5.15%",
  },
  rectangle17: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  p: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "0%",
    bottom: "83.78%",
    left: "91.33%",
  },
  rectangle18: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  o: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "10.03%",
    bottom: "83.78%",
    left: "81.3%",
  },
  rectangle19: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  symbol19: {
    position: "absolute",
    marginTop: -13.58,
    top: "50%",
    left: "40.63%",
    fontSize: 23,
    letterSpacing: -1,
    fontFamily: "Inter-Regular",
    color: "#121212",
    textAlign: "center",
  },
  i: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "20.33%",
    bottom: "83.78%",
    left: "71%",
  },
  rectangle20: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  u: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "30.35%",
    bottom: "83.78%",
    left: "60.98%",
  },
  rectangle21: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  y: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "40.65%",
    bottom: "83.78%",
    left: "50.68%",
  },
  rectangle22: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  t: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "50.68%",
    bottom: "83.78%",
    left: "40.65%",
  },
  rectangle23: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  r: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "60.98%",
    bottom: "83.78%",
    left: "30.35%",
  },
  rectangle24: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  e: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "71%",
    bottom: "83.78%",
    left: "20.33%",
  },
  rectangle25: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  w: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "81.3%",
    bottom: "83.78%",
    left: "10.03%",
  },
  rectangle26: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 6,
    backgroundColor: "#fcfcfe",
    shadowColor: "#a8a8a8",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 1,
  },
  q: {
    position: "absolute",
    height: "16.22%",
    width: "8.67%",
    top: "0%",
    right: "91.33%",
    bottom: "83.78%",
    left: "0%",
  },
  keys: {
    position: "absolute",
    height: "89%",
    width: "98.4%",
    top: "2.75%",
    right: "0.8%",
    bottom: "8.25%",
    left: "0.8%",
  },
  homeIndicator: {
    position: "absolute",
    marginLeft: -66.5,
    bottom: 8,
    left: "50%",
    borderRadius: 100,
    backgroundColor: "#191052",
    width: 134,
    height: 5,
  },
  homeIndicatorLight: {
    position: "absolute",
    top: 257,
    left: 0,
    width: 375,
    height: 34,
  },
  lightAlphabetic: {
    position: "relative",
    backgroundColor: "#d1d5db",
    width: 390,
    height: 299,
  },
  frame6: {
    width: 390,
    height: 353,
    overflow: "hidden",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 27,
  },
  iphone143: {
    position: "relative",
    backgroundColor: "#fafafa",
    flex: 1,
    width: "100%",
    overflow: "hidden",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
  },
});

export default IPhone144;
